[package]
name = "stage2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "stage2"
path = "src/stage2.rs"

[[bin]]
name = "svsm"
path = "src/svsm.rs"

[dependencies]
bitflags = "1.3.2"
memoffset = "0.6.5"

[build-dependencies]
cc = "1.0.46"
