[package]
name = "svsm"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stage2"
path = "src/stage2.rs"
test = false

[[bin]]
name = "svsm"
path = "src/svsm.rs"
test = false

[lib]
test = true
doctest = false

[dependencies]
bitflags = "1.3.2"
gdbstub = { version = "0.6.6", default-features = false }
gdbstub_arch = "0.2.4"
log = { version = "0.4.17", features = ["max_level_info", "release_max_level_info"] }
packit = { git = "https://github.com/coconut-svsm/packit", version = "0.1.0" }

[build-dependencies]
cc = "1.0.46"

[features]
default = ["enable-stacktrace"]
enable-stacktrace = []
enable-gdb = []
